### ISSUE TITLE
Add support for 64 bit Linux

### ISSUE THREAD

**Issue by stewsters** [seniorjoinu/wirehair-wrapper#2]
When I run the example code for prodigy it does not work on Linux.  I believe this is because this wrapper does not yet include all the major OSes.

Caused by: java.io.IOException: Native library (linux-x86-64/libwirehair.so) not found in resource path

I saw you mention it in your readme, but I am adding an issue so I get notified when its added.

**Comment by seniorjoinu** [comment]
It actually works. You need to get binaries from `src/test/resources` and place them under your project's `resources`.

**Comment by seniorjoinu** [comment]
Finally figured out how `jni` actually works. Binaries for `linux-x86-64` and `win32-x86-64` are now bundled inside. Everything should work. 

This native stuff kills me 🌵
